export const FETCH_COURSES_LIST_LOADING = "FETCH_COURSES_LIST_LOADING"
export const FETCH_COURSES_LIST_SUCCESS = "FETCH_COURSES_LIST_SUCCESS"
export const FETCH_COURSES_LIST_FAIL = "FETCH_COURSES_LIST_FAIL"

export const CHOOSE_COURSE_TYPE = "CHOOSE_COURSE_TYPE";
export const FETCH_USER_CLICK = "FETCH_USER_CLICK";
export const EDIT_COURSE_CLICK = "EDIT_COURSE_CLICK"
export const ADD_COURSE_CLICK  = "ADD_COURSE_CLICK";

export const ADD_COURSE_LOADING = "ADD_COURSE_LOADING";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL";

export const FETCH_USERS_LIST_OF_COURSE_LOADING = "FETCH_USERS_LIST_OF_COURSE_LOADING";
export const FETCH_USERS_LIST_OF_COURSE_SUCCESS = "FETCH_USERS_LIST_OF_COURSE_SUCCESS";
export const FETCH_USERS_LIST_OF_COURSE_FAIL = "FETCH_USERS_LIST_OF_COURSE_FAIL";

export const FETCH_USER_PENDING_LIST_LOADING = "FETCH_USER_PENDING_LIST_LOADING";
export const FETCH_USER_PENDING_LIST_SUCCESS = "FETCH_USER_PENDING_LIST_SUCCESS";
export const FETCH_USER_PENDING_LIST_FAIL  = "FETCH_USER_PENDING_LIST_FAIL";

export const FETCH_USER_DENIED_LIST_LOADING = "FETCH_USER_DENIED_LIST_LOADING";
export const FETCH_USER_DENIED_LIST_SUCCESS = "FETCH_USER_DENIED_LIST_SUCCESS";
export const FETCH_USER_DENIED_LIST_FAIL = "FETCH_USER_DENIED_LIST_FAIL";

export const APPROVE_USER_PENDING_LOADING = "APPROVE_USER_PENDING_LOADING"
export const APPROVE_USER_PENDING_SUCCESS = "APPROVE_USER_PENDING_SUCCESS";
export const APPROVE_USER_PENDING_FAIL = "APPROVE_USER_PENDING_FAIL";

export const DISAPPROVE_USER_LOADING = "DISAPPROVE_USER_LOADING";
export const DISAPPROVE_USER_SUCCESS = "DISAPPROVE_USER_SUCCESS";
export const DISAPPROVE_USER_FAIL = "DISAPPROVE_USER_FAIL";

export const UPLOAD_IMAGE_LOADING = "UPLOAD_IMAGE_LOADING";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";

export const DELETE_COURSE_LOADING = "DELETE_COURSE_LOADING";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";
