export const GET_COURSES_DETAIL_REQUEST = "GET_COURSES_DETAIL_REQUEST";
export const GET_COURSES_DETAIL_SUCCESS = "GET_COURSES_DETAIL_SUCCESS";
export const GET_COURSES_DETAIL_FAILURE = "GET_COURSES_DETAIL_FAILURE";