export const GET_COURSES_INDEX_REQUEST = "GET_COURSES_INDEX_REQUEST";
export const GET_COURSES_INDEX_SUCCESS = "GET_COURSES_INDEX_SUCCESS";
export const GET_COURSES_INDEX_FAILURE = "GET_COURSES_INDEX_FAILURE";