export const ENROLL_COURSE_LOADING = "ENROLL_COURSE_LOADING"
export const ENROLL_COURSE_FAIL = "ENROLL_COURSE_FAIL"
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS"

export const FETCH_USER_LOADING = "FETCH_USER_LOADING"
export const FETCH_USER_FAIL = "FETCH_USER_FAIL"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"