export const FETCH_INFO_CLICK = "FETCH_INFO_CLICK"
export const EDIT_USER_CLICK = "EDIT_USER_CLICK"
export const ADD_USER_CLICK = "ADD_USER_CLICK"

export const FETCH_USERS_START = "FETCH_USERS_START"
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL"

export const FETCH_COURSE_APPROVAL_PENDING_START = "FETCH_COURSE_APPROVAL_PENDING_START"
export const FETCH_COURSE_APPROVAL_PENDING_FAIL = "FETCH_COURSE_APPROVAL_PENDING_FAIL"
export const FETCH_COURSE_APPROVAL_PENDING_SUCCESS = "FETCH_COURSE_APPROVAL_PENDING_SUCCESS"

export const DELETE_USER_START = "DELETE_USER_START"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"

export const ADD_USER_START = "ADD_USER_START"
export const ADD_USER_FAIL = "ADD_USER_FAIL"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS" 

export const APPROVE_COURSE_PENDING_START = "APPROVE_COURSE_PENDING_START"
export const APPROVE_COURSE_PENDING_FAIL = "APPROVE_COURSE_PENDING_FAIL"
export const APPROVE_COURSE_PENDING_SUCCESS = "APPROVE_COURSE_PENDING_SUCCESS"

export const FETCH_COURSE_APPROVED_START = "FETCH_COURSE_APPROVED_START"
export const FETCH_COURSE_APPROVED_FAIL = "FETCH_COURSE_APPROVED_FAIL"
export const FETCH_COURSE_APPROVED_SUCCESS = "FETCH_COURSE_APPROVED_SUCCESS"

export const DISAPPROVE_COURSE_START = "DISAPPROVE_COURSE_START"
export const DISAPPROVE_COURSE_FAIL = "DISAPPROVE_COURSE_FAIL"
export const DISAPPROVE_COURSE_SUCCESS = "DISAPPROVE_COURSE_SUCCESS"

export const FETCH_COURSE_NONE_ENROLL_START = "FETCH_COURSE_NONE_ENROLL_START"
export const FETCH_COURSE_NONE_ENROLL_FAIL = "FETCH_COURSE_NONE_ENROLL_FAIL"
export const FETCH_COURSE_NONE_ENROLL_SUCCESS = "FETCH_COURSE_NONE_ENROLL_SUCCESS"

export const SEARCH_USER_START = "SEARCH_USER_START"
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"