export const FETCH_USER_DETAIL_LOADING = "FETCH_USER_DETAIL_LOADING"
export const FETCH_USER_DETAIL_SUCCESS = "FETCH_USER_DETAIL_SUCCESS"
export const FETCH_USER_DETAIL_FAIL = "FETCH_USER_DETAIL_FAIL "